# ==========================================================
# PROFIL PROD — MySQL
# Bonne pratique DevOps : configuration externalisée,
# les valeurs sont lues depuis les variables d’environnement.
# ==========================================================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# update : met à jour le schéma sans supprimer les données
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Désactiver la console H2 en production
spring.h2.console.enabled=false
